### PR TITLE
fix double notification for incoming sms on kitkat, refs #21

### PR DESCRIPTION
**Pull request by felixb**
Please review and verify this fix.

http://ub0r.de/files/074a554ef5ee4487615234795a13393e284cce83-SMSdroid-release.apk

### CODE REVIEW

**Comment by Cactus-World** [comment]
Solves playing the sound double but does not fix the cutting off of the sound itself.

**Comment by felixb** [comment]
the latest commit should prevent cutting of the notification sound

http://ub0r.de/files/1d0b713d40eb6cfb765b93a3c31adb28af302d9f-SMSdroid-release.apk

**Comment by rphair** [comment]
I'm having this problem as well (a new user, just installed this weekend & donated yesterday).  Since it's been 6 weeks, can these changes be merged in with the mainstream app on the Play Store?  Can't really recommend this to friends & clients if the properly working app is only available from an APK.  I'll test the APK myself if that's what you need before pushing it out to the world.

**Comment by rphair** [comment]
Neither APK link above is currently working.  I'm ready to test this if developer will tell me how to get an installable APK which includes the latest commit.  Experiencing the problem on Nexus 5 with latest CM13.

**Comment by felixb** [comment]
Well, I was waiting for feedback like yours. Can you please describe, how exactly the latest version is not working?

**Comment by rphair** [comment]
I mean when I click either of the APK links above, I get a "404 Not Found" error for the link, i.e. that the content itself is missing from the web host at ub0r.de ...

**Comment by felixb** [comment]
I accidentally removed the files on my server. Here is a new build with the same code base as above:

http://ub0r.de/files/d3f2dbeb429c3eb29ca9f741b4782748aa1d598c-SMSdroid-logRelease.apk

**Comment by rphair** [comment]
thanks; just installed the APK immediately above and it fixes the double-notification problem on my device.

**Comment by felixb** [comment]
thanks for testing. I merged the code into the master branch. i'll try to release within a few days.

**Pull request merged**
